### ISSUE TITLE
config file doesn't download

### ISSUE THREAD

**Issue by Fatvallon** [Tera-Shiraneko/auto-club-rewards#1]
please include config file in manifest coz it doesn't download ty.

**Comment by Tera-Shiraneko** [comment]
If I add config file to manifest it will be overwritten if you change it.

**Comment by Tera-Shiraneko** [comment]
Just copy paste the code into an empty config.json file.

**Comment by Tera-Shiraneko** [comment]
And add your name between the ""

**Comment by Fatvallon** [comment]
{
	"files": {
		"config.json": {
			"hash": "49e97a17a4f48d5598358d4d624c589232d6d6725235dc3bc8ae08dc630a5d80",
			"overwrite": false
},

u can do it this way not to be overwritten

**Comment by Tera-Shiraneko** [comment]
Problem should be gone now.
